name = "TerminalWidgets"
uuid = "0f3ad5c8-04a9-4c13-9905-e12e559c4777"
authors = ["Ben Lauwens <ben.lauwens@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
TerminalBase = "0e6ac781-a4f6-46c1-b458-cd01e5135a7a"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
